#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-YAML-Syck
Version  : 1.30
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/T/TO/TODDR/YAML-Syck-1.30.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TODDR/YAML-Syck-1.30.tar.gz
Source1  : http://http.debian.net/debian/pool/main/liby/libyaml-syck-perl/libyaml-syck-perl_1.30-1.debian.tar.xz
Summary  : 'Fast, lightweight YAML loader and dumper'
Group    : Development/Tools
License  : MIT
Requires: perl-YAML-Syck-lib
Requires: perl-YAML-Syck-license
Requires: perl-YAML-Syck-man

%description
No detailed description available

%package lib
Summary: lib components for the perl-YAML-Syck package.
Group: Libraries
Requires: perl-YAML-Syck-license

%description lib
lib components for the perl-YAML-Syck package.


%package license
Summary: license components for the perl-YAML-Syck package.
Group: Default

%description license
license components for the perl-YAML-Syck package.


%package man
Summary: man components for the perl-YAML-Syck package.
Group: Default

%description man
man components for the perl-YAML-Syck package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n YAML-Syck-1.30
mkdir -p %{_topdir}/BUILD/YAML-Syck-1.30/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/YAML-Syck-1.30/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-YAML-Syck
cp COPYING %{buildroot}/usr/share/doc/perl-YAML-Syck/COPYING
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/JSON/Syck.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/YAML/Dumper/Syck.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/YAML/Loader/Syck.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/YAML/Syck.pm

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/YAML/Syck/Syck.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-YAML-Syck/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/JSON::Syck.3
/usr/share/man/man3/YAML::Syck.3
