#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-YAML-Syck
Version  : 1.31
Release  : 8
URL      : https://cpan.metacpan.org/authors/id/T/TO/TODDR/YAML-Syck-1.31.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TODDR/YAML-Syck-1.31.tar.gz
Source1  : http://http.debian.net/debian/pool/main/liby/libyaml-syck-perl/libyaml-syck-perl_1.30-1.debian.tar.xz
Summary  : 'Fast, lightweight YAML loader and dumper'
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: perl-YAML-Syck-lib = %{version}-%{release}
Requires: perl-YAML-Syck-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
No detailed description available

%package dev
Summary: dev components for the perl-YAML-Syck package.
Group: Development
Requires: perl-YAML-Syck-lib = %{version}-%{release}
Provides: perl-YAML-Syck-devel = %{version}-%{release}

%description dev
dev components for the perl-YAML-Syck package.


%package lib
Summary: lib components for the perl-YAML-Syck package.
Group: Libraries
Requires: perl-YAML-Syck-license = %{version}-%{release}

%description lib
lib components for the perl-YAML-Syck package.


%package license
Summary: license components for the perl-YAML-Syck package.
Group: Default

%description license
license components for the perl-YAML-Syck package.


%prep
%setup -q -n YAML-Syck-1.31
cd ..
%setup -q -T -D -n YAML-Syck-1.31 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/YAML-Syck-1.31/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-YAML-Syck
cp COPYING %{buildroot}/usr/share/package-licenses/perl-YAML-Syck/COPYING
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-YAML-Syck/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/JSON/Syck.pm
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/YAML/Dumper/Syck.pm
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/YAML/Loader/Syck.pm
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/YAML/Syck.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/JSON::Syck.3
/usr/share/man/man3/YAML::Syck.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/auto/YAML/Syck/Syck.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-YAML-Syck/COPYING
/usr/share/package-licenses/perl-YAML-Syck/deblicense_copyright
